### ISSUE TITLE
Tip-of-tree amaranth not compatible with tip of amaranth-boards

### ISSUE THREAD

**Issue by thirtythreeforty** [amaranth-lang/amaranth#676]
When I try to include Amaranth in a Poetry project:

```toml
[tool.poetry]
name = "test-poetry"
description = ""
version = "0.1.0"
authors = ["George Hilliard <thirtythreeforty@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
amaranth = {git = "https://github.com/amaranth-lang/amaranth", branch = "main"}
amaranth-boards = {git = "https://github.com/amaranth-lang/amaranth-boards", branch = "main"}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

I get an error:
```
  SolverProblemError

  Because amaranth-boards (rev main) depends on amaranth (>=0.2,<0.4)
   and test-poetry depends on amaranth (branch main), amaranth-boards is forbidden.
  So, because test-poetry depends on amaranth-boards (branch main), version solving failed.
```

I think this has to do something with [this line in setup.py](https://github.com/amaranth-lang/amaranth-boards/blob/8e2615765e255144403431ca95c5cdf6c78eb638/setup.py#L24
) although I don't know what the intent is.
